### ISSUE TITLE
Bad loop syntax

### ISSUE THREAD

**Issue by Yehouda** [BnMcGn/claxy#1]
https://github.com/BnMcGn/claxy/blob/1467186c4741a5adc50804f2f3197253eb2fa162/claxy.lisp#L29
The **using** clause must be after the **of|in** clause, so the `using (hash-value v)` bit needs to be after the `headers`, like that:

` (loop for k being the hash-key  of headers using (hash-value v)`

Look for **for-as-hash** in [loop](http://www.lispworks.com/documentation/HyperSpec/Body/m_loop.htm)

**Comment by BnMcGn** [comment]
Thanks for the bug report. Fix posted.

SBCL accepts either ordering without complaint. We'll cater to Lispworks, which is evidently more correct.
